### ISSUE TITLE
Visualization module issues

### ISSUE THREAD

**Issue by simonspa** [simonspa/allpix-squared#39]
In gitlab by @simonspa on May 29, 2017, 15:57

a) Minor detail:

```
|15:55:15.118|  (STATUS) Finalization completed
|15:55:15.118|  (STATUS) Executed 36 instantiations in 1 minutes 32 seconds, spending 89% of time in slowest instantiation VisualizationGeant4
```
this is rather funny but not very useful.

b) When quitting the viz window, I get a stack trace:

```
 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 5 (Thread 0x7f89cf9af700 (LWP 663)):
#0  0x00007f8a058d84aa in __GI___waitpid (pid=704, stat_loc=stat_loc
entry=0x7f89cf9a6c40, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007f8a058512cb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007f8a054ffd49 in TUnixSystem::Exec(char const*) (shellcmd=<optimized out>, this=0x563f5bfa34f0) at /home/simonspa/software/root/core/unix/src/TUnixSystem.cxx:2117
#3  0x00007f8a054ffd49 in TUnixSystem::StackTrace() (this=0x563f5bfa34f0) at /home/simonspa/software/root/core/unix/src/TUnixSystem.cxx:2404
#4  0x00007f8a0550240c in TUnixSystem::DispatchSignals(ESignals) (this=0x563f5bfa34f0, sig=kSigSegmentationViolation) at /home/simonspa/software/root/core/unix/src/TUnixSystem.cxx:3624
#5  0x00007f8a058417f0 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f89e9fcb1d0 in QAbstractEventDispatcherPrivate::allocateTimerId() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f89e9fcb829 in QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f89e9ffc04e in QObject::startTimer(int, Qt::TimerType) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f89e213a947 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#10 0x00007f89e1ae748d in  () at /lib/x86_64-linux-gnu/libdbus-1.so.3
#11 0x00007f89e1ad1e82 in dbus_connection_send_with_reply () at /lib/x86_64-linux-gnu/libdbus-1.so.3
#12 0x00007f89e213a573 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#13 0x00007f89e9ffb359 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007f89e9fce88b in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f89e9fd102d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f89ea022b03 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f89e7b24377 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f89e7b245e0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f89e7b2468c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007f89ea022f0f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f89e9fcc88a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f89e9df9fe3 in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007f89e212f5c5 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#24 0x00007f89e9dfec98 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007f8a03e156da in start_thread (arg=0x7f89cf9af700) at pthread_create.c:456
#26 0x00007f8a0591417f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 4 (Thread 0x7f89d5615700 (LWP 662)):
#0  0x00007f8a0590818d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f89e7b24576 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f89e7b24902 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f89d97c2476 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f89e7b4bf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f8a03e156da in start_thread (arg=0x7f89d5615700) at pthread_create.c:456
#6  0x00007f8a0591417f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 3 (Thread 0x7f89d5e16700 (LWP 661)):
#0  0x00007f8a0590818d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f89e7b24576 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f89e7b2468c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f89e7b246d1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f89e7b4bf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f8a03e156da in start_thread (arg=0x7f89d5e16700) at pthread_create.c:456
#6  0x00007f8a0591417f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 2 (Thread 0x7f89e10d4700 (LWP 660)):
#0  0x00007f8a0590818d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f89e5d06c62 in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f89e5d088d7 in xcb_wait_for_event () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f89e46f0ed9 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f89e9dfec98 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f8a03e156da in start_thread (arg=0x7f89e10d4700) at pthread_create.c:456
#6  0x00007f8a0591417f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 1 (Thread 0x7f8a065ab980 (LWP 651)):
#0  0x00007f8a03e1b510 in pthread_cond_wait

GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f89e9dffb4b in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007f89e9dfe83e in QThread::wait(unsigned long) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f89e212cd56 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#4  0x00007f89e212ce19 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#5  0x00007f8a05846270 in __run_exit_handlers (status=0, listp=0x7f8a05bcd5d8 <__exit_funcs>, run_list_atexit=run_list_atexit
entry=true, run_dtors=run_dtors
entry=true) at exit.c:83
#6  0x00007f8a058462ca in __GI_exit (status=<optimized out>) at exit.c:105
#7  0x00007f8a0582c3f8 in __libc_start_main (main=0x563f5ab0f570 <main(int, char const**)>, argc=3, argv=0x7fff28223378, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff28223368) at ../csu/libc-start.c:325
#8  0x0000563f5ab108aa in _start ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f89e9fcb1d0 in QAbstractEventDispatcherPrivate::allocateTimerId() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f89e9fcb829 in QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f89e9ffc04e in QObject::startTimer(int, Qt::TimerType) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f89e213a947 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#10 0x00007f89e1ae748d in  () at /lib/x86_64-linux-gnu/libdbus-1.so.3
#11 0x00007f89e1ad1e82 in dbus_connection_send_with_reply () at /lib/x86_64-linux-gnu/libdbus-1.so.3
#12 0x00007f89e213a573 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#13 0x00007f89e9ffb359 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007f89e9fce88b in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f89e9fd102d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f89ea022b03 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f89e7b24377 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f89e7b245e0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f89e7b2468c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007f89ea022f0f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f89e9fcc88a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f89e9df9fe3 in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007f89e212f5c5 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#24 0x00007f89e9dfec98 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007f8a03e156da in start_thread (arg=0x7f89cf9af700) at pthread_create.c:456
#26 0x00007f8a0591417f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

===========================================================
```

**Comment by simonspa** [comment]
In gitlab by @Koensw on May 29, 2017, 16:11

a) I noticed yes, but I think it is not worth fixing 

b) Weird... There is no reference at all to any AP2 thing. This looks like a QT issue, unless we are messing with the stack / heap somehow.

**Comment by simonspa** [comment]
In gitlab by @simonspa on May 30, 2017, 10:57

```WARNING: Viewpoint direction is very close to the up vector direction.
  Consider setting the up vector to obtain definable behaviour.```

**Comment by simonspa** [comment]
In gitlab by @simonspa on May 30, 2017, 11:37

* [x] Move parameters from G4Constrcution to Visualization
* [x] Move simple view to Visualization
* [x] Currently only last event is displayed, but should display all events stacked up

**Comment by simonspa** [comment]
In gitlab by @Koensw on Jun 13, 2017, 16:16

`WARNING: Viewpoint direction is very close to the up vector direction.
  Consider setting the up vector to obtain definable behaviour.`

This we can only fix if we create our own Qt module and fetch this message. I don't think that is on the top of the list at the moment.

**Comment by simonspa** [comment]
In gitlab by @Koensw on Jun 13, 2017, 16:16

See !19 for all other changes

**Comment by simonspa** [comment]
In gitlab by @Koensw on Jun 13, 2017, 18:21

mentioned in merge request !19

**Comment by simonspa** [comment]
In gitlab by @Koensw on Jun 14, 2017, 09:40

Closing now !19 is merged.

**Comment by simonspa** [comment]
In gitlab by @Koensw on Jun 14, 2017, 09:40

closed
